- include_tasks: setup.yml

- include_tasks: "tf_module.yml"
  vars:
    state: "present"

- include_tasks: "antlet_nic.yml"
  vars:
    antlet_name: "{{ item.dname }}"
    mac: "{{ antlet_nic_macs[item.dname]['mac'] }}"
    nic_type: "bridge"
    source: "{{ antlet_nic_macs[item.dname]['source'] }}"
    nic_model: "virtio"
  when: 'item.dname in antlet_nic_macs'
  with_items:  "{{ tf_nodes.outputs.antlet.value }}"

- include_tasks: "antlet_start.yml"
  vars:
      antlet_name: "{{ item.dname }}" 
  with_items:  "{{ tf_nodes.outputs.antlet.value }}"