version: '1'
services:
  antsle:
    # swagger-url: http://192.168.1.122:3000/swagger.json
    # swagger-url: /Users/manny/git/ansible-roles/antsle/files/terraform/api/swagger.yaml
    swagger-url: /tmp/swagger.yaml
    insecure_skip_verify: true