  - name: Download terraform archive Linux {{ terraform_arch }} bits
    get_url:
      url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_{{ terraform_arch }}.zip
      dest: /tmp/terraform-{{terraform_version}}.zip

  - name: Install unzip to unarchive terraform
    package:
      name: unzip
      state: present
  
  - name: Create Terraform directory
    file:
      path: "{{terraform_dir}}"
      state: directory
    register: terraform_directory

  - name: Unarchive Terraform archive
    unarchive:
      src: /tmp/terraform-{{terraform_version}}.zip
      dest: "{{ terraform_dir }}"
      copy: no
    when: terraform_directory is changed

  - name: Adding terraform command to user path
    file: 
      src: "{{terraform_dir}}/terraform"
      dest: /usr/bin/terraform
      state: link

  - name: Install Open API Provider
    shell: |
      export PROVIDER_NAME=antsle  && curl -fsSL https://raw.githubusercontent.com/dikhan/terraform-provider-openapi/master/scripts/install.sh | bash -s -- --provider-name $PROVIDER_NAME
      