
---
- name: Prepare
  hosts: instance
  gather_facts: no
  vars:
    terraform_version: "0.12.24"
    terraform_dir: /opt/terraform
    terraform_arch: "amd64"
    go_tarball: "go1.14.2.linux-amd64.tar.gz"
    go_download_location: "https://storage.googleapis.com/golang/{{ go_tarball }}"
    go_tarball_checksum: "sha256:6272d6e940ecb71ea5636ddb5fab3933e087c1356173c61f4a803895e947ebb3"
    go_version_target: "go version go1.14.2 linux/amd64"
    set_go_path: true
  tasks:
  - debug:
      msg: "Host name {{ inventory_hostname }}"
  
  - include_tasks: tasks/install_golang.yml

  - include_tasks: tasks/install_terraform.yml